name: firebasedemo
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^8.3.0
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  dio: ^5.5.0+1
  dio_smart_retry: ^6.0.0
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  duration: ^3.0.13
  envied: ^0.5.4+1
  file_picker: ^8.0.6
  flash: ^3.1.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
    
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  form_field_validator: ^1.1.0
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  lottie: ^3.1.2
  multiple_result: ^5.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  platform_info: ^4.0.2
  razorpay_flutter: ^1.3.7
  responsive_framework: ^1.4.0
  shimmer: ^3.0.0
  talker_dio_logger: ^4.3.4
  talker_flutter: ^4.3.4
  toggle_switch: ^2.3.0
  velocity_x: ^4.2.1
  firebase_core: ^3.4.0
  fcm_config: ^3.6.0

dev_dependencies:
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0
  custom_lint: ^0.6.4
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_lint: ^2.3.10
  riverpod_test: ^0.1.5
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
