// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUARLLuH4IiVfu7yi8USjWexmPKeL7hY',
    appId: '1:475791226813:web:645e8704800ce37c14c4d4',
    messagingSenderId: '475791226813',
    projectId: 'fir-9ead6',
    authDomain: 'fir-9ead6.firebaseapp.com',
    storageBucket: 'fir-9ead6.appspot.com',
    measurementId: 'G-V9F3S8LQHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wOwjcUjQo8N4pAGH65g3rqZPKs-Yr0I',
    appId: '1:475791226813:android:fab2ac52ede3e6e814c4d4',
    messagingSenderId: '475791226813',
    projectId: 'fir-9ead6',
    storageBucket: 'fir-9ead6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQBZQe4bymrUp1fDw255Dse2tsNdinWS8',
    appId: '1:475791226813:ios:d6a4ea84b2c3c97f14c4d4',
    messagingSenderId: '475791226813',
    projectId: 'fir-9ead6',
    storageBucket: 'fir-9ead6.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQBZQe4bymrUp1fDw255Dse2tsNdinWS8',
    appId: '1:475791226813:ios:d6a4ea84b2c3c97f14c4d4',
    messagingSenderId: '475791226813',
    projectId: 'fir-9ead6',
    storageBucket: 'fir-9ead6.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeUARLLuH4IiVfu7yi8USjWexmPKeL7hY',
    appId: '1:475791226813:web:597a90ac07c4dd5514c4d4',
    messagingSenderId: '475791226813',
    projectId: 'fir-9ead6',
    authDomain: 'fir-9ead6.firebaseapp.com',
    storageBucket: 'fir-9ead6.appspot.com',
    measurementId: 'G-QRG7SB6BBE',
  );
}
